version: "3.8"
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    # volumes:
    #   - ./dbtmp/data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    restart: always